A few improvements for the RF522 implementation
jdevelop/golang-rpi-extras pull request #4
Opened 2018-10-09 01:13 UTC by vkorn

* Error handling during the init -- so we don't proceed if device is locked by something else 
* Antenna gain setter -- setting gain power 0-7
* Close method to stop SPI device -- releasing opened device

2018-10-09 11:52 UTC, jdevelop requested changes

2018-10-09 11:52 UTC, jdevelop commented on rf522/Rf522.go
> +	stop          chan bool
can we use `chan interface{}` here? More idiomatic :)

2018-10-09 11:53 UTC, jdevelop commented
Also the driver was largely migrated to https://github.com/google/periph/ so it would be nice if you can send the PR there.

2018-10-09 17:45 UTC, vkorn commented
@jdevelop changed chan to `interface{}`

I've tried periph's implementation but can't get it to work -- it simply locks the device completely upon initialization. The only way to bring it back -- reboot RPi itself. I didn't have time to look into device opening logic in periph yet.

2018-10-10 00:38 UTC, jdevelop commented
Interesting, I ported the code for that library and it works fine there.

2018-10-10 00:38 UTC, jdevelop approved these changes

2018-10-10 00:38 UTC, merged